CREATE DATABASE IF NOT EXISTS questfypro;

USE questfypro;

CREATE TABLE IF NOT EXISTS perguntas(
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	descrpt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS respostas(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_pergunta INT NOT NULL,
	correta BOOL NOT NULL
);